<?php

namespace Tests\Feature;

use App\models\BoxList;
use App\User;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Facades\Auth;
use Tests\TestCase;

class ItemTest extends TestCase
{
    use DatabaseTransactions;
    Protected $email = 'first1@gmail.com';
    Protected $password = 12345678;
    Protected $user;

    function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->user =User::firstOrCreate(['email'=>$this->email],[
            'email' => $this->email,
            'name' => 'first',
            'password' => bcrypt($this->password),
        ]);
        Auth::login($this->user);
        //======check if login or not===========//
        $this->assertAuthenticatedAs($this->user);

    }

    /**
     * test add new name with not wrong
     *
     */

    public function testAddNewName(){
        $body=[
            'name'=>'wrwer',
            'user_id'=>$this->user->id
        ];
        $response=$this->post('Lists',$body);
        $response->assertStatus(200);
    }
    /**
     * Test update for list1 or 2
     *
     */
    public function testUpdateType(){
        $item =BoxList::firstOrCreate(['name'=>'testName'],[
            'Name' => 'testName',
            'user_id'=>$this->user->id
        ]);
        $body=[
            'id'=>$item->id
        ];
        $response=$this->post('ChangeList',$body);
        $response->assertStatus(200);
    }
}
